server:
  servlet:
    context-path: /api/v1

spring:
  liquibase:
    change-log: classpath:database/changelog.xml
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.order_by.default_null_ordering: last
  datasource:
    url: jdbc:h2:mem:testdb;MODE=Oracle;INIT=create schema IF NOT EXISTS ISAI
    username: root
    password:
